num-particles: 10000

# total-steps: 40000
# total-steps: 32768
# total-steps: 28672
total-steps: 24576
# total-steps: 22528
# total-steps: 16384
# total-steps: 8192
# total-steps: 1000

<<<<<<<< HEAD:src/particle_model/config.yaml
end-time: 2
========
end-time: 3
>>>>>>>> 9ad98bc (untracked files):particle_model/config.yaml
scheme: euler
# scheme: milstein

make-animation: False
# store-plot: False
store-plot: True
show-end: False
